#!/usr/bin/env lua

function get_temp()
    return io.popen('sensors'):read("*all");
end

sensors_temp = get_temp()
temp = string.match(sensors_temp, "Package id 0:  %+(%d+%.%d)°C?")

if tonumber(temp) > 70
    then
        print(string.format(" %s°C", temp))
elseif tonumber(temp) < 40
    then
        print(string.format(" %s°C", temp))
else
    print(string.format(" %s°C", temp))
end


os.exit()
