patch:
  show_notifications_via_notification_center: true
  us_keyboard_layout: true                               # 美式键盘布局
  show_notifications_when: appropriate                   # 状态通知，适当，也可设为全开（always）全关（never）

  style:
    color_scheme: light                                  # 配色方案名称
    #alpha: 0.99                                         # 透明度

  preset_color_schemes:
    light:
      name: register                                     # 作者名
      author: "register <registerdedicated@gmail.com>"   # 作者

      horizontal: true                                   # 候选条横向显示
      inline_preedit: true                               # 启用内嵌编码模式，候选条首行不显示拼音
      candidate_format: "%c.\u2005%@\u2005"              # 用 1/6 em 空格 U+2005 来控制编号 %c 和候选词 %@ 前后的空间。

      corner_radius: 5                                   # 候选条圆角半径
      border_height: 7                                   # 窗口边界高度，大于圆角半径才生效
      border_width: 7                                    # 窗口边界宽度，大于圆角半径才生效
      back_color: 0xFFFFFF                               # 候选条背景色
      border_color: 0xE0B693                             # 边框色
      font_face: "PingFangSC-Regular"                    # 候选词字体
      font_point: 18                                     # 预选栏文字字号
      label_font_face: "PingFangSC-Light"                # 候选词编号字体
      label_font_point: 14                               # 预选栏编号字号
      label_color: 0x999999                              # 预选栏编号颜色
      candidate_text_color: 0x000000                     # 预选项文字颜色
      text_color: 0x000000                               # 拼音行文字颜色，24位色值，16进制，BGR顺序
      comment_text_color: 0x999999                       # 拼音等提示文字颜色
      hilited_text_color: 0xFF6941                       # 高亮拼音 (需要开启内嵌编码)
      hilited_candidate_text_color: 0xFF6941             # 第一候选项文字颜色
      hilited_candidate_back_color: 0xFFFFFF             # 第一候选项背景背景色
      hilited_candidate_label_color: 0xFF6941            # 第一候选项编号颜色
      hilited_comment_text_color: 0xFF6941               # 注解文字高亮

  app_options:
    com.blacktree.Quicksilver: &a
      ascii_mode: false
    com.googlecode.iterm2: *a
    com.alfredapp.Alfred: *a
    com.runningwithcrayons.Alfred-2: *a
    org.vim.MacVim: *a
    com.apple.Terminal: *a
