version: "3.7"

services:
    postgresql:
        image: postgres:9.6-alpine
        container_name: postgres
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        restart: always
        environment:
            POSTGRES_USER: "root"
            POSTGRES_PASSWORD: "goodluck@123"
        networks:
            m_net:
                ipv4_address: 172.16.0.4

    mariadb:
        image: mariadb
        container_name: mariadb
        volumes:
            - ./data/mysql:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-goodluck@123}
            - MYSQL_USER=${MYSQL_USER:-root}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD:-goodluck@123}
        networks:
            m_net:
                ipv4_address: 172.16.0.6
networks:
    m_net:
        ipam:
            driver: default
            config:
                - subnet: "172.16.0.0/24"
