[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'taigacute/spaceline.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
depends = 'vim-devicons'
hook_add='source ~/.config/nvim/plugins/lightline.vim'

[[plugins]]
repo = 'neoclide/coc.nvim'
merge = 0
build = 'yarn install --frozen-lockfile'
hook_add = 'source ~/.config/nvim/plugins/coc-config.vim'
hook_source = '''
'''

[[plugins]]
repo = 'wsdjeg/dein-ui.vim'

# [[plugins]]
# repo = 'yuttie/comfortable-motion.vim' # 平滑滚动

[[plugins]]
repo = 'joshdick/onedark.vim'

# [[plugins]]
# repo = 'morhetz/gruvbox'
#
# [[plugins]]
# repo = 'sainnhe/vim-color-forest-night'

[[plugins]]
repo = 'taigacute/gruvbox9'

[[plugins]]
repo = 'mengelbrecht/lightline-bufferline'
hook_add='source ~/.config/nvim/plugins/lightline.vim'
on_ft = ['python', 'json', 'toml', 'yaml', 'c', 'cpp', 'golang', 'rust', 'shell']
