[[plugins]]
repo = 'scrooloose/nerdtree'
on_map = { n ='<Plug>'}
depends = ['vim-devicons','vim-nerdtree-syntax-highlight']
hook_source = 'source ~/.config/nvim/plugins/nerdtree.vim'

[[plugins]]
repo = 'tiagofumo/vim-nerdtree-syntax-highlight'
hook_add = '''
    let g:NERDTreeSyntaxDisableDefaultExtensions = 1
    let g:NERDTreeDisableExactMatchHighlight = 1
    let g:NERDTreeDisablePatternMatchHighlight = 1
    let g:NERDTreeSyntaxEnabledExtensions = ['go', 'py', 'html', 'css', 'jsx', 'js', 'vim','json','md']
'''

[[plugins]]
repo = 'luochen1990/rainbow'
on_ft = ['python','js','jsx','html','css','go','vim','toml']
hook_source = 'let g:rainbow_active = 1'

[[plugins]]
repo = 'jiangmiao/auto-pairs'
hook_ad = 'source ~/.config/nvim/plugins/auto-pairs.vim'
on_ft = ['python', 'javascript', 'golang', 'c', 'cpp', 'rust', 'toml']

[[plugins]]
repo = 'scrooloose/nerdcommenter'
hook_add = 'source ~/.config/nvim/plugins/nerdcommenter.vim'
on_ft =['vim','json','go','html','js','jsx','py','css','less','tmpl','toml','xml','sql', 'i3', 'yaml', 'c', 'cpp']

[[plugins]]
repo = 'w0rp/ale'
hook_add = 'source ~/.config/nvim/plugins/vim-ale.vim'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
hook_source = 'source ~/.config/nvim/plugins/vim-go.vim'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['json']
hook_add = 'let g:vim_json_syntax_conceal = 0'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft= ['toml']

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'mhinz/vim-startify'
on_cmd = 'Startify'
depends = 'vim-devicons'
hook_add ='source ~/.config/nvim/plugins/startify.vim'
hook_post_source = '''
function! StartifyEntryFormat()
    return 'WebDevIconsGetFileTypeSymbol(absolute_path) ." ". entry_path'
endfunction
'''
[[plugins]]
repo = 'majutsushi/tagbar'
# on_cmd = ['TagbarToggle']
on_ft = ['rust','java', 'go', 'c', 'python']

[[plugins]]
repo = 'xuhdev/SingleCompile'
on_ft = ['rust', 'java', 'c', 'cpp', 'python', 'lua', 'elixir', 'erlang', 'go']

[[plugins]]
repo = 'PotatoesMaster/i3-vim-syntax'
on_ft = 'i3'

[[plugins]]
repo = 'Yggdroot/LeaderF'
on_cmd = ['./install.sh']

[[plugins]]
repo = 'voldikss/vim-translate-me'
hook_add = 'source ~/.config/nvim/plugins/translate.vim'
on_ft = ['python', 'vim', 'toml', 'markdown', 'c', 'cc', 'cpp', 'rust']

[[plugins]]
repo = 'tenfyzhong/CompleteParameter.vim'
on_ft = ['golang', 'c', 'cpp', 'python', 'rust']
hook_add = 'source ~/.config/nvim/plugins/completeParameter.vim'

[[plugins]]
repo = 'liuchengxu/vista.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'
on_ft = ['python', 'c', 'go', 'rust','html','css','vim','javascript','javascript.jsx']
hook_add = 'source ~/.config/nvim/plugins/indentLine.vim'

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_ft = ['markdown', 'pandoc.markdown', 'rmd']
build = 'cd app & yarn install'

[[plugins]]
repo = 'Shougo/defx.nvim'
on_cmd = 'Defx'
hook_source = 'source ~/.config/nvim/plugins/defx.vim'

[[plugins]]
repo = 'kristijanhusak/defx-icons'
on_source = 'defx.nvim'

[[plugins]]
repo = 'dag/vim-fish'
on_ft = ['fish']

[[plugins]]
repo = 'kovetskiy/sxhkd-vim'
on_ft = ['sxhkd']

[[plugins]]
repo = 'yuttie/comfortable-motion.vim'
on_func ='comfortable_motion#flick'
hook_add = '''
let g:comfortable_motion_no_default_key_mappings = 1
let g:comfortable_motion_impulse_multiplier = 1
'''

[[plugins]]
repo = 'mengelbrecht/lightline-bufferline'
hook_add='source ~/.config/nvim/plugins/lightline.vim'


